"""initial schema

Revision ID: 669ec03caa54
Revises: 
Create Date: 2026-04-18 10:38:51.321216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '669ec03caa54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_owner', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('repo_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('commit_sha', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('recommendation', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('total_findings', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_commit_sha'), 'reviews', ['commit_sha'], unique=False)
    op.create_index(op.f('ix_reviews_pr_number'), 'reviews', ['pr_number'], unique=False)
    op.create_index(op.f('ix_reviews_repo_name'), 'reviews', ['repo_name'], unique=False)
    op.create_index(op.f('ix_reviews_repo_owner'), 'reviews', ['repo_owner'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('original_severity', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('suggestion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('code_fix', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('diff_position', sa.Integer(), nullable=True),
    sa.Column('comment_destination', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('mapping_failed', sa.Boolean(), nullable=False),
    sa.Column('github_comment_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_agent_name'), 'findings', ['agent_name'], unique=False)
    op.create_index(op.f('ix_findings_category'), 'findings', ['category'], unique=False)
    op.create_index(op.f('ix_findings_file_path'), 'findings', ['file_path'], unique=False)
    op.create_index(op.f('ix_findings_fingerprint'), 'findings', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_findings_github_comment_id'), 'findings', ['github_comment_id'], unique=False)
    op.create_index(op.f('ix_findings_review_id'), 'findings', ['review_id'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_review_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_github_comment_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_fingerprint'), table_name='findings')
    op.drop_index(op.f('ix_findings_file_path'), table_name='findings')
    op.drop_index(op.f('ix_findings_category'), table_name='findings')
    op.drop_index(op.f('ix_findings_agent_name'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_reviews_repo_owner'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_repo_name'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_pr_number'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_commit_sha'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
