from typing import Any, Mapping

class Formatter:
    """Formats raw code review findings into GitHub-flavored Markdown."""

    @staticmethod
    def build_summary_comment(findings: list[Mapping[str, Any]], pr_metadata: dict[str, Any] | None = None) -> str:
        """Builds the main PR summary comment, including any unmapped global findings."""
        if not findings:
            return "## 🤖 AI Code Review\n\n✅ No issues found! Excellent work."
        
        lines = [
            "## 🤖 AI Code Review Summary",
            "",
            f"**Total Findings:** {len(findings)}",
            "",
        ]

        # Categorize by destination
        inline_findings = [f for f in findings if f.get("comment_destination") == "inline" or f.get("diff_position") is not None]
        summary_findings = [f for f in findings if f not in inline_findings]

        if inline_findings:
            lines.append(f"- 📝 **{len(inline_findings)} inline comments** added to specific lines of code.")
        
        if summary_findings:
            lines.append(f"- ⚠️ **{len(summary_findings)} global/unmapped findings** (see below).")
        
        lines.append("")
        
        if summary_findings:
            lines.append("### 🔍 Global Findings")
            for finding in summary_findings:
                severity = finding.get("severity", 3)
                category = str(finding.get("category", "General")).title()
                title = finding.get("title", "Issue")
                desc = finding.get("description", "")
                
                sev_icon = "🔴" if severity >= 4 else ("🟡" if severity == 3 else "⚪")
                
                lines.append(f"**{sev_icon} [{category}] {title} (Severity: {severity})**")
                if desc:
                    lines.append(f"> {desc}")
                
                if finding.get("suggestion"):
                    lines.append("\n**Suggestion:**")
                    lines.append(f"```text\n{finding['suggestion']}\n```")
                lines.append("")
                
        lines.append("---\n*Review generated by AI Code Review Agent*")
        return "\n".join(lines)

    @staticmethod
    def build_inline_comment(finding: Mapping[str, Any]) -> str:
        """Builds a Markdown comment intended for a specific line/diff position."""
        severity = finding.get("severity", 3)
        category = str(finding.get("category", "General")).title()
        title = finding.get("title", "Issue")
        desc = finding.get("description", "")
        
        sev_icon = "🔴" if severity >= 4 else ("🟡" if severity == 3 else "⚪")
        
        lines = [f"**{sev_icon} [{category}] {title}**"]
        if desc:
            lines.append("")
            lines.append(desc)
            
        code_fix = finding.get("code_fix")
        if code_fix:
            lines.append("")
            lines.append("```suggestion")
            lines.append(str(code_fix))
            lines.append("```")
        elif finding.get("suggestion"):
            lines.append("")
            lines.append(f"**Suggestion:** {finding['suggestion']}")
            
        return "\n".join(lines)
